project:
  title: "The Conceptual Leap"
  type: website
  output-dir: .site
  preview:
    port: 5152
    browser: false
  render:
    - "**/*.qmd"        # render qmd
    - "**/*.md"         # render md
    - "!**/master*.md"  # explicitly ignore master*.md anywhere 
    - "!**/master*.qmd" # explicitly ignore master*.md anywhere 
    - "!drafts/*"       # exclude paths
  post-render:
    - rhythmpress sitemap   # Sun, 31 Aug 2025 03:22:23 +0900 runs after every build
resources:
  - Ads.txt
  - _redirects
  - 404.html
  - attachments/*
  - common-ly/*.ly
  - common-ly/shared/*.ly

website:
  title: "The Conceptual Leap"
  description: "The websites that explains my personal thoughts."
  site-url: "https://theconceptualleap.com/"
  site-path: /
  page-footer:
    left: "Â© 2025 - The Conceptual Leap - All rights reserved."
    right: |
      |
      [About the Publisher](/about/publisher/en/) |
      [About This Site](/about/theconceptualleap/en/) |
      [Contact](/contact/en/) |
      [Send a Message](/contact-form/en/) |
      [Disclaimer](/disclaimer/en/) |
      <br/>
      |
      [Privacy Policy](/privacy-policy/en/) |
      <a href="/cookies/en/">Cookie Policy</a> |
      <a href="#" id="cookie-settings" rel="nofollow">Cookie Preferences</a> |

  page-navigation: true     # show Previous / Next buttons in the footer
  bread-crumbs: true
  navbar:
    # logo: /attachments/site-logo-light.png
    right:
      - href: index.qmd
        text: "Home"
  sidebar:
    style: "docked"
    # logo: /attachments/site-logo-light.png
    collapse-level: 1
    contents: []
metadata:
  lilypond-preamble: "common-ly/lilypond-preamble.ly"
format:
  html:
    pandoc:
      from: markdown+raw_html
    theme:
      light : [ cosmo,  .assets/websites/theme.scss, .assets/websites/theme-light.scss ]
      dark  : [ darkly, .assets/websites/theme.scss, .assets/websites/theme-dark.scss  ]
    lightbox: true
    reference-location: block
    filters:
      - filters/meta-dates.lua
      - filters/include-files.lua
      - filters/lilypond.lua
      - filters/remove-softbreaks.lua
#      - filters/obsidian-image-dimensions.lua
    css: assets/styles.css
    toc: true
    toc-location: right
    toc-depth: 7
    toc-expand: 1
    include-in-header:
      - text: |
          <script async type="module" src="/assets/ats4u-twitter-video.mjs"></script>
          <link href="/assets/groovespace.css" rel="stylesheet" />
          <script async type="module" src="/assets/groovespace.mjs"></script>
          <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          <script async type="module" src="/assets/toc-ul.mjs"></script>
          <script async type="module" src="/assets/cookie-settings.mjs"></script>
    page-layout: full      # still allows custom width via CSS
    grid:
      sidebar-width: 450px
      body-width: 500px
      margin-width: 450px
      gutter-width: 0.5em
metadata-files:
  - _sidebar-en.generated.yml
  - _metadata.yml
